stages:
  - build-unit-test
  - deploy

compile:
  stage: build-unit-test
  image: r8n01:5000/coe-maven-centos:latest
  script:
    - mvn verify -B
  tags:
    - docker

deploy:
  stage: deploy
  image: r8n01:5000/coe-maven-centos:latest
  script:
    - mvn deploy -Pcoe-release -B
  tags:
    - docker
  only:
    - master
